spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mustache:
    suffix: .html
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true